transformations:
#  - id: 'tag_0'
#    frame_id: 'camera_color_optical_frame'
#    matrix:
#      - [0.0, 1.0, 0.0, 1.0]
#      - [0.0, 0.0, -1.0, 0.0]
#      - [-1.0, 0.0, 0.0, 0.0]
#      - [0.0, 0.0, 0.0, 1.0]
#  - id: 'tag_2'
#    frame_id: 'camera_color_optical_frame'
#    matrix:
#      - [ 0.0, -1.0, 0.0, 1.0 ]
#      - [ 0.0, 0.0, -1.0, 5.0 ]
#      - [ -1.0, 0.0, 0.0, 0.5 ]
#      - [ 0.0, 0.0, 0.0, 1.0 ]
#  - id: 'tag_13'
#    frame_id: 'camera_color_optical_frame'
#    matrix:
#      - [ 0.0, 1.0, 0.0, 1.0 ]
#      - [ 0.0, 0.0, -1.0, 2.0 ]
#      - [ -1.0, 0.0, 0.0, 0.5 ]
#      - [ 0.0, 0.0, 0.0, 1.0 ]
#  - id: 'camera_color_optical_frame'
#    frame_id: 'map'
#    matrix:
#      - [1.0, 0.0, 0.0, 0.0]
#      - [0.0, 0.0, 1.0, 0.0]
#      - [0.0, -1.0, 0.0, 0.15]
#      - [0.0, 0.0, 0.0, 1.0]
#  - id: 'camera_color_optical_frame'
#    frame_id: 'base_link'
#    matrix:
#      - [ 0.0, 0.0, 1.0, 0.0 ]
#      - [ 1.0, 0.0, 0.0, 0.0 ]
#      - [ 0.0, -1.0, 0.0, 0.0 ]
#      - [ 0.0, 0.0, 0.0, 1.0 ]
#  - id: 'aptag_0'
#    frame_id: 'map'
#    matrix:
#      - [ 0.0, 1.0, 0.0, -0.28]
#      - [ -1.0, 0.0, 0.0, 2.08 ]
#      - [ 0.0, 0.0, 1.0, 0.47 ]
#      - [ 0.0, 0.0, 0.0, 1.0 ]
#  - id: 'aptag_2'
#    frame_id: 'map'
#    matrix:
#      - [ 0.0, 1.0, 0.0, 1.08 ]
#      - [ -1.0, 0.0, 0.0, 1.65 ]
#      - [ 0.0, 0.0, 1.0, 0.15 ]
#      - [ 0.0, 0.0, 0.0, 1.0 ]
#  - id: 'aptag_13'
#    frame_id: 'map'
#    matrix:
#      - [ -1.0, 0.0, 0.0, 1.66 ]
#      - [ 0.0, -1.0, 0.0, 0.6 ]
#      - [ 0.0, 0.0, 1.0, 0.35 ]
#      - [ 0.0, 0.0, 0.0, 1.0 ]
  - id: 'unity'
    frame_id: 'map'
    matrix:
      - [ 1.0, .0, 0.0, 0 ]
      - [ 0.0, 1.0, 0.0, 0 ]
      - [ 0.0, 0.0, 1.0, 0 ]
      - [ 0.0, 0.0, 0.0, 1.0 ]