string patient_name
string[] locations
string door_location
string outside_location
string medicine_location
string bedroom_location
string patient_location
string eat_location
int32 door_open # -1 means value is none
int32 door_motion_sensor # -1 means value is none
int32 took_medicine # -1 means value is none
int32 ate_breakfast # -1 means value is none
int32 ate_lunch # -1 means value is none
int32 ate_dinner # -1 means value is none
int32 too_late_to_leave # -1 means value is none
int32 time_to_take_medicine # -1 means value is none
int32 time_to_eat_breakfast # -1 means value is none
int32 time_to_eat_lunch # -1 means value is none
int32 time_to_eat_dinner # -1 means value is none



