pioneer1:
  x: -2.0
  y: -11.0
  a: 0.0
  planner: 'rags'
pioneer2:
  x: -2.0
  y: 9.5
  a: 0.0
  planner: 'rags'
pioneer3:
  x: 5.5
  y: -11.5
  a: 0.0
  planner: 'rags'
pioneer4:
  x: 2.5
  y: 3.5
  a: 0.0
  planner: 'rags'
pioneer5:
  x: 2.5
  y: 18.0
  a: 0.0
  planner: 'rags'
pioneer6:
  x: 9.0
  y: 3.5
  a: 0.0
  planner: 'rags'
pioneer7:
  x: 8.0
  y: 15.5
  a: -1.57
  planner: 'rags'
pioneer8:
  x: 13.5
  y: -6.5
  a: 1.57
  planner: 'rags'
pioneer9:
  x: 13.5
  y: 3.5
  a: 0.0
  planner: 'rags'
pioneer10:
  x: 13.5
  y: 19.5
  a: -1.57
  planner: 'rags'
